### ISSUE TITLE
Issue with non-English characters

### ISSUE THREAD

**Issue by hailinzeng** [LibreSolar/md-manual-template#7]
Hi, I am new to LaTex. `make pdf` errors out if the markdown file contains CJK characters.

    Error producing PDF.
    ! Package inputenc Error: Unicode character 本 (U+672C)
    (inputenc)                not set up for use with LaTeX.

    See the inputenc package documentation for explanation.
    Type  H <return>  for immediate help.
     ...

    l.392 本

    Try running pandoc with --pdf-engine=xelatex.
    make: *** [pdf] Error 43`

**Comment by martinjaeger** [comment]
Hi. Unfortunately I don't know an immediate solution how to fix this in latex. This might be a general Latex issue and not a pandoc issue, so I hope you can find some further information on the internet. If you found a solution, please let me know.

**Comment by hailinzeng** [comment]
@martinjaeger Hi, I have found a solution to this. For Chinese characters, just add the following option to pandoc.

		--pdf-engine=xelatex \
		-V CJKmainfont='Songti SC'\
